compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: null
    vyper:
        version: null
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0